name: radio_kpop_brasil
description: Rádio K-POP Brasil
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.35
  audio_session: ^0.1.25

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
