platform :ios, '12.0'

flutter_application_path = File.expand_path('..', __dir__)
podhelper_path = File.join(flutter_application_path, '.dart_tool', 'flutter_build', 'ios', 'podhelper.rb')

if File.exist?(podhelper_path)
  load podhelper_path
else
  puts "warning: podhelper.rb not found at #{podhelper_path}"
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(flutter_application_path)

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
