platform :ios, '12.0'

flutter_application_path = File.expand_path('..', __dir__)
load File.join(flutter_application_path, '.flutter-plugins')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
