name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Clean previous builds
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock .dart_tool build

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Precache Flutter iOS engine
        run: flutter precache --ios

      - name: Generate iOS project (includes podhelper.rb)
        run: flutter build ios --release --no-codesign

      - name: Verificar se podhelper.rb existe
        run: |
          if [ ! -f .ios/Flutter/podhelper.rb ]; then
            echo "❌ ERRO: podhelper.rb NÃO gerado!"
            exit 1
          else
            echo "✅ podhelper.rb existe."
          fi

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --verbose

      - name: Build IPA (unsigned)
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/ios/ipa/*.ipa
