name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Flutter pub get
        run: flutter pub get

      - name: Verify plugins generated
        run: |
          ls -l .flutter-plugins
          ls -l .dart_tool/flutter_build/ios

      - name: Flutter clean
        run: flutter clean

      - name: Flutter build ios (to generate podhelper.rb)
        run: flutter build ios --release --no-codesign

      - name: Verify podhelper.rb exists
        run: |
          if [ ! -f ".dart_tool/flutter_build/ios/podhelper.rb" ]; then
            echo "❌ podhelper.rb not found!"
            exit 1
          fi

      - name: Adjust Podfile
        run: |
          sed -i.bak -E "s|load File.join\\(flutter_application_path, '.dart_tool', 'flutter_build', 'ios', 'podhelper.rb'\\)|podhelper_path = File.join(flutter_application_path, '.dart_tool', 'flutter_build', 'ios', 'podhelper.rb'); load podhelper_path if File.exist?(podhelper_path)|" ios/Podfile

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build IPA
        run: flutter build ipa --release --no-codesign
